[tool.poetry]
name = "panorama-sidekick"
version = "0.1.0"
description = ""
authors = ["John Torres <johnnyjamestorres@outlook.com>"]
readme = "README.md"
packages = [{include = "panorama_sidekick"}]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
